import cv2 as cv
import numpy as np
img=cv.imread('OpenCV/ken.png')
blank=np.zeros(img.shape,dtype='uint8')
cv.imshow("blank",blank)
cv.imshow('ken',img)
gray= cv.cvtColor(img,cv.COLOR_BGR2GRAY)
cv.imshow('kengray',gray)
# blur= cv.GaussianBlur(gray,(3,3),cv.BORDER_DEFAULT)
# cv.imshow('blur',blur)
# canny =cv.Canny(blur,125,175)
# cv.imshow('canny',canny)
tet, thresh=cv.threshold(gray,125,255,cv.THRESH_BINARY)
cv.imshow('threshhold',thresh)
# countour,hierachies=cv.findContours(canny,cv.RETR_LIST,cv.CHAIN_APPROX_NONE)
contour,hierachies=cv.findContours(thresh,cv.RETR_LIST,cv.CHAIN_APPROX_NONE)
print(f'{len(contour)} contours(s) found')
cv.drawContours(blank,contour,-1,(0,0,255),1)
cv.imshow("show contour",blank)
cv.waitKey(0)